/**
 * EpisodeSummaries.js — 3-sentence LLM summary per episode.
 */
import { loadJSON } from '../lib/data.js'

function escHtml(s) { return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;') }

export async function renderEpisodeSummariesPage(container, store) {
  container.innerHTML = `<div class="loading"><div class="spinner"></div>Loading episode summaries...</div>`
  try {
    const data = await loadJSON('episode_summaries.json')
    renderPage(container, data)
  } catch (e) {
    container.innerHTML = `
      <div class="page-header">
        <h1>📝 Episode Summaries</h1>
        <p>Three-sentence summaries of each episode, generated by LLM.</p>
      </div>
      <div class="card" style="text-align:center;padding:48px">
        <div style="font-size:48px;margin-bottom:16px">⏳</div>
        <div style="font-size:18px;font-weight:600;margin-bottom:8px">Episode summaries not yet generated</div>
        <div style="font-size:14px;color:var(--color-muted)">Run <code>episode_summariser.py</code> with MiniMax API key to generate <code>episode_summaries.json</code></div>
      </div>
    `
  }
}

function renderPage(container, data) {
  const summaries = data.summaries || []

  const looksCorrupted = summaries.length === 0 ||
    summaries.every(s => s.summary.length > 500 ||
      /we need to|the user asks|format:|the prompt|the instruction/i.test(s.summary))
  if (looksCorrupted) {
    container.innerHTML = `
      <div class="page-header">
        <h1>📝 Episode Summaries</h1>
        <p>Three-sentence summaries of each episode, generated by LLM.</p>
      </div>
      <div class="card" style="text-align:center;padding:48px">
        <div style="font-size:48px;margin-bottom:16px">⏳</div>
        <div style="font-size:18px;font-weight:600;margin-bottom:8px">Episode summaries not yet generated</div>
        <div style="font-size:14px;color:var(--color-muted)">Run <code>episode_summariser.py</code> with MiniMax API key to generate <code>episode_summaries.json</code></div>
      </div>
    `
    return
  }

  container.innerHTML = `
    <div class="page-header">
      <h1>📝 Episode Summaries</h1>
      <p>3-sentence summary of each of the ${summaries.length} episodes. Generated by LLM from question content.</p>
    </div>

    <div style="margin-bottom:24px">
      <input type="text" id="sumSearch" placeholder="Search summaries..." style="padding:10px;border-radius:8px;border:1px solid var(--color-border);width:100%;max-width:400px">
    </div>

    <div id="sumGrid" style="display:grid;grid-template-columns:repeat(auto-fill,minmax(380px,1fr));gap:16px"></div>
  `

  const grid = container.querySelector('#sumGrid')

  function render(filter) {
    const filtered = summaries.filter(s =>
      !filter || s.episode.includes(filter) || s.summary.toLowerCase().includes(filter.toLowerCase())
    )
    grid.innerHTML = filtered.slice(0, 80).map(s => `
      <div class="card">
        <div style="font-size:13px;color:var(--color-muted);margin-bottom:8px">
          <a href="/episodes?ep=${s.episode}" class="nav-link" data-link>${s.episode}</a>
        </div>
        <div style="font-size:15px;line-height:1.6">${escHtml(s.summary)}</div>
      </div>
    `).join('')
    if (filtered.length > 80) {
      grid.innerHTML += `<div style="padding:16px;color:var(--color-muted)">Showing 80 of ${filtered.length} results — refine your search</div>`
    }
  }

  render('')
  container.querySelector('#sumSearch').addEventListener('input', e => render(e.target.value))
}